### PR TITLE
update to use Module#prepend

### PR DESCRIPTION
**Pull request by mathieujobin**

### CODE REVIEW

**Comment by mathieujobin** [comment]
I use this branch already for a almost 3 years... 

I'm about to add a fix for ruby 3.0

I really wish I could get this one merged and released on rubygems without doing a gem rename.

thank you

**Comment by mathieujobin** [comment]
@jeffp @tomriley @akira 

よろしくおねがいします

**Comment by akira** [comment]
Hey @mathieujobin, 

Sorry I didn't realize this was still used.  Do you mind adding checks to this so the unit tests run?  If so I can merge it. 

Thanks, 
@akira

**Comment by akira** [comment]
@mathieujobin I don't see the checks running for some reason?

**Comment by mathieujobin** [comment]
@akira Done https://github.com/payrollhero/validationgroup/actions/runs/3545602513/jobs/5953871636

Github actions runs on my fork, I think you need to approve to make them run on yours.

Rails 5.2 -> 7.0

**Review by akira — APPROVED** [review]

**Comment by mathieujobin** [comment]
Thanks for the merge ! it ran indeed. https://github.com/akira/validationgroup/actions/runs/3545615270

let me know when its pushed to rubygems

thank you

**Comment by akira** [comment]
@mathieujobin Do you happen to know if there any changes needed for gemspec?  Trying to publish via workflows, seems to be failing though. (been a while since I've worked in Ruby 😄 )

**Comment by akira** [comment]
@mathieujobin was able to publish it 🎉  Thanks for the PR!

**Pull request merged**
